package com.tianrui.service.admin.bean;

import com.tianrui.service.bean.IModel;
/**
 * 
 * @类描述：货物档案
 * @创建人：tank
 * @创建时间：2016年4月22日下午4:44:20
 *
 * @Modifier：guyuke
 * @ModifyTime：2016年5月29日下午4:55:00
 * @Memo：分页字段增加及注释修改
 *
 */
public class FileCargo implements IModel {
	
	private static final long serialVersionUID = -2339847197298728504L;
	
    /**
     * 主键UUID
     */
    private String id;
    //被调用次数
    private String count;

    /**
     * 所属组织名称 
     */
    private String organizationname;

    /**
     * 所属组织id
     */
    private String organizationid;

    /**
     * 货物分类
     */
    private String cargotype;

    /**
     * 货物名称
     */
    private String cargoname;

    /**
     * 货物编码
     * @mbggenerated
     */
    private String cargono;

    /**
     * 货物助记码
     */
    private String zjm;

    /**
     *  货物状态（0-停用；1-启用；2-已删除）
     */
    private String status;

    /**
     * 主计量单位
     * @mbggenerated
     */
    private String measure;

    /**
     * 货物规格
     */
    private String specifications;

    /**
     * 货物型号
     */
    private String model;

    /**
     * 货物图片路径
     */
    private String imagepath;

    /**
     * 创建者 
     */
    private String creator;

    /**
     * 创建时间
     */
    private Long createtime;

    /**
     * 修改者
     */
    private String modifier;

    /**
     * 修改时间
     */
    private Long modifytime;

    /**
     * 自定义项1
     */
    private String desc1;

    /** 
     * 自定义项2
     */
    private String desc2;

    /**
     * 自定义项3
     */
    private String desc3;

    /**
     * 自定义项4
     */
    private String desc4;

    /** 分页开始位置 */
    private Integer start;
    
    /** 分页数据行数 */
    private Integer limit;
    
    /**
     *
     * @return the value of file_cargo.ID
     *
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.ID
     *
     * @param id the value for file_cargo.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.organizationname
     *
     * @return the value of file_cargo.organizationname
     *
     * @mbggenerated
     */
    public String getOrganizationname() {
        return organizationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.organizationname
     *
     * @param organizationname the value for file_cargo.organizationname
     *
     * @mbggenerated
     */
    public void setOrganizationname(String organizationname) {
        this.organizationname = organizationname == null ? null : organizationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.organizationid
     *
     * @return the value of file_cargo.organizationid
     *
     * @mbggenerated
     */
    public String getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.organizationid
     *
     * @param organizationid the value for file_cargo.organizationid
     *
     * @mbggenerated
     */
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid == null ? null : organizationid.trim();
    }

    public String getCount() {
		return count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.cargotype
     *
     * @return the value of file_cargo.cargotype
     *
     * @mbggenerated
     */
    public String getCargotype() {
        return cargotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.cargotype
     *
     * @param cargotype the value for file_cargo.cargotype
     *
     * @mbggenerated
     */
    public void setCargotype(String cargotype) {
        this.cargotype = cargotype == null ? null : cargotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.cargoname
     *
     * @return the value of file_cargo.cargoname
     *
     * @mbggenerated
     */
    public String getCargoname() {
        return cargoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.cargoname
     *
     * @param cargoname the value for file_cargo.cargoname
     *
     * @mbggenerated
     */
    public void setCargoname(String cargoname) {
        this.cargoname = cargoname == null ? null : cargoname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.cargono
     *
     * @return the value of file_cargo.cargono
     *
     * @mbggenerated
     */
    public String getCargono() {
        return cargono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.cargono
     *
     * @param cargono the value for file_cargo.cargono
     *
     * @mbggenerated
     */
    public void setCargono(String cargono) {
        this.cargono = cargono == null ? null : cargono.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.zjm
     *
     * @return the value of file_cargo.zjm
     *
     * @mbggenerated
     */
    public String getZjm() {
        return zjm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.zjm
     *
     * @param zjm the value for file_cargo.zjm
     *
     * @mbggenerated
     */
    public void setZjm(String zjm) {
        this.zjm = zjm == null ? null : zjm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.status
     *
     * @return the value of file_cargo.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.status
     *
     * @param status the value for file_cargo.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.measure
     *
     * @return the value of file_cargo.measure
     *
     * @mbggenerated
     */
    public String getMeasure() {
        return measure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.measure
     *
     * @param measure the value for file_cargo.measure
     *
     * @mbggenerated
     */
    public void setMeasure(String measure) {
        this.measure = measure == null ? null : measure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.specifications
     *
     * @return the value of file_cargo.specifications
     *
     * @mbggenerated
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.specifications
     *
     * @param specifications the value for file_cargo.specifications
     *
     * @mbggenerated
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications == null ? null : specifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.model
     *
     * @return the value of file_cargo.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.model
     *
     * @param model the value for file_cargo.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.imagepath
     *
     * @return the value of file_cargo.imagepath
     *
     * @mbggenerated
     */
    public String getImagepath() {
        return imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.imagepath
     *
     * @param imagepath the value for file_cargo.imagepath
     *
     * @mbggenerated
     */
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath == null ? null : imagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.creator
     *
     * @return the value of file_cargo.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.creator
     *
     * @param creator the value for file_cargo.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.createtime
     *
     * @return the value of file_cargo.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.createtime
     *
     * @param createtime the value for file_cargo.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.modifier
     *
     * @return the value of file_cargo.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.modifier
     *
     * @param modifier the value for file_cargo.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.modifytime
     *
     * @return the value of file_cargo.modifytime
     *
     * @mbggenerated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.modifytime
     *
     * @param modifytime the value for file_cargo.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.DESC1
     *
     * @return the value of file_cargo.DESC1
     *
     * @mbggenerated
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.DESC1
     *
     * @param desc1 the value for file_cargo.DESC1
     *
     * @mbggenerated
     */
    public void setDesc1(String desc1) {
        this.desc1 = desc1 == null ? null : desc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.DESC2
     *
     * @return the value of file_cargo.DESC2
     *
     * @mbggenerated
     */
    public String getDesc2() {
        return desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.DESC2
     *
     * @param desc2 the value for file_cargo.DESC2
     *
     * @mbggenerated
     */
    public void setDesc2(String desc2) {
        this.desc2 = desc2 == null ? null : desc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.DESC3
     *
     * @return the value of file_cargo.DESC3
     *
     * @mbggenerated
     */
    public String getDesc3() {
        return desc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.DESC3
     *
     * @param desc3 the value for file_cargo.DESC3
     *
     * @mbggenerated
     */
    public void setDesc3(String desc3) {
        this.desc3 = desc3 == null ? null : desc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_cargo.DESC4
     *
     * @return the value of file_cargo.DESC4
     *
     * @mbggenerated
     */
    public String getDesc4() {
        return desc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_cargo.DESC4
     *
     * @param desc4 the value for file_cargo.DESC4
     *
     * @mbggenerated
     */
    public void setDesc4(String desc4) {
        this.desc4 = desc4 == null ? null : desc4.trim();
    }
    
	/**
	 * 获取分页开始位置
	 * @return start
	 */
	public Integer getStart() {
		return start;
	}
	
	/**
	 * 设置分页开始位置
	 * @param newStart
	 */
	public void setStart(Integer newStart) {
		this.start = newStart;
	}
	
	/**
	 * 获取分页数据行数
	 * @return limit
	 */
	public Integer getLimit() {
		return limit;
	}
	
	/**
	 * 设置分页数据行数
	 * @param newLimit
	 */
	public void setLimit(Integer newLimit) {
		this.limit = newLimit;
	}
}