package com.tianrui.service.admin.bean;

public class FilePositoin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.ID
     *
     * @mbggenerated
     */
    private String id;
    /** 被使用次数*/
    private String count;
    /** 备注*/
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.orgId
     *
     * @mbggenerated
     */
    private String orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.opc
     *
     * @mbggenerated
     */
    private String opc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.op
     *
     * @mbggenerated
     */
    private String op;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.occ
     *
     * @mbggenerated
     */
    private String occ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.oc
     *
     * @mbggenerated
     */
    private String oc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.oac
     *
     * @mbggenerated
     */
    private String oac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.oa
     *
     * @mbggenerated
     */
    private String oa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.addr
     *
     * @mbggenerated
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.lat
     *
     * @mbggenerated
     */
    private Integer lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.lng
     *
     * @mbggenerated
     */
    private Integer lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_position.createtime
     *
     * @mbggenerated
     */
    private Long createtime;
    
    private Short status;
    private Integer start;
    private Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.ID
     *
     * @return the value of file_position.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.ID
     *
     * @param id the value for file_position.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.orgId
     *
     * @return the value of file_position.orgId
     *
     * @mbggenerated
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.orgId
     *
     * @param orgid the value for file_position.orgId
     *
     * @mbggenerated
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.name
     *
     * @return the value of file_position.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.name
     *
     * @param name the value for file_position.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.opc
     *
     * @return the value of file_position.opc
     *
     * @mbggenerated
     */
    public String getOpc() {
        return opc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.opc
     *
     * @param opc the value for file_position.opc
     *
     * @mbggenerated
     */
    public void setOpc(String opc) {
        this.opc = opc == null ? null : opc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.op
     *
     * @return the value of file_position.op
     *
     * @mbggenerated
     */
    public String getOp() {
        return op;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.op
     *
     * @param op the value for file_position.op
     *
     * @mbggenerated
     */
    public void setOp(String op) {
        this.op = op == null ? null : op.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.occ
     *
     * @return the value of file_position.occ
     *
     * @mbggenerated
     */
    public String getOcc() {
        return occ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.occ
     *
     * @param occ the value for file_position.occ
     *
     * @mbggenerated
     */
    public void setOcc(String occ) {
        this.occ = occ == null ? null : occ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.oc
     *
     * @return the value of file_position.oc
     *
     * @mbggenerated
     */
    public String getOc() {
        return oc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.oc
     *
     * @param oc the value for file_position.oc
     *
     * @mbggenerated
     */
    public void setOc(String oc) {
        this.oc = oc == null ? null : oc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.oac
     *
     * @return the value of file_position.oac
     *
     * @mbggenerated
     */
    public String getOac() {
        return oac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.oac
     *
     * @param oac the value for file_position.oac
     *
     * @mbggenerated
     */
    public void setOac(String oac) {
        this.oac = oac == null ? null : oac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.oa
     *
     * @return the value of file_position.oa
     *
     * @mbggenerated
     */
    public String getOa() {
        return oa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.oa
     *
     * @param oa the value for file_position.oa
     *
     * @mbggenerated
     */
    public void setOa(String oa) {
        this.oa = oa == null ? null : oa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.addr
     *
     * @return the value of file_position.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.addr
     *
     * @param addr the value for file_position.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.lat
     *
     * @return the value of file_position.lat
     *
     * @mbggenerated
     */
    public Integer getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.lat
     *
     * @param lat the value for file_position.lat
     *
     * @mbggenerated
     */
    public void setLat(Integer lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.lng
     *
     * @return the value of file_position.lng
     *
     * @mbggenerated
     */
    public Integer getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.lng
     *
     * @param lng the value for file_position.lng
     *
     * @mbggenerated
     */
    public void setLng(Integer lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.creator
     *
     * @return the value of file_position.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.creator
     *
     * @param creator the value for file_position.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_position.createtime
     *
     * @return the value of file_position.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_position.createtime
     *
     * @param createtime the value for file_position.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public String getCount() {
		return count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	public Short getStatus() {
		return status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}


    
}