package com.tianrui.service.admin.bean;

import com.tianrui.service.bean.IModel;
/**
 * @字段：serialVersionUID
 * @功能描述：
 * @创建人：tank
 * @创建时间：2016年4月22日下午4:39:05
 */
public class FileOrg  implements IModel{
    /**
     * id
     */
    private String id;

    /**
     * 组织名称
     */
    private String organizationname;
    /**
     * 组织被使用次数
     */
    private String count;

    /**
     * 组织类型0-天瑞旗下；1-山水旗下；2-社会资源
     */
    private String organizationtype;

    /**
     *  组织编码
     */
    private String organizationno;

    /**
     *  组织状态（1-启用；2-已禁用）
     */
    private String status;

    /**
     * 创建者 
     */
    private String creator;

    /**
     * 创建时间
     */
    private Long createtime;

    /**
     * 修改者 
     */
    private String modifier;

    /**
     * 修改时间S
     */
    private Long modifytime;

    /**
     *
     * @mbggenerated
     */
    private String desc1;

    /**
     *
     * @mbggenerated
     */
    private String desc2;

    /**
     *
     * @mbggenerated
     */
    private String desc3;

    /**
     *
     * @mbggenerated
     */
    private String desc4;

    private Integer start;
    private Integer limit;
    
    /**
     *
     * @return the value of file_org.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    public String getCount() {
		return count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.ID
     *
     * @param id the value for file_org.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.organizationname
     *
     * @return the value of file_org.organizationname
     *
     * @mbggenerated
     */
    public String getOrganizationname() {
        return organizationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.organizationname
     *
     * @param organizationname the value for file_org.organizationname
     *
     * @mbggenerated
     */
    public void setOrganizationname(String organizationname) {
        this.organizationname = organizationname == null ? null : organizationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.organizationtype
     *
     * @return the value of file_org.organizationtype
     *
     * @mbggenerated
     */
    public String getOrganizationtype() {
        return organizationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.organizationtype
     *
     * @param organizationtype the value for file_org.organizationtype
     *
     * @mbggenerated
     */
    public void setOrganizationtype(String organizationtype) {
        this.organizationtype = organizationtype == null ? null : organizationtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.organizationno
     *
     * @return the value of file_org.organizationno
     *
     * @mbggenerated
     */
    public String getOrganizationno() {
        return organizationno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.organizationno
     *
     * @param organizationno the value for file_org.organizationno
     *
     * @mbggenerated
     */
    public void setOrganizationno(String organizationno) {
        this.organizationno = organizationno == null ? null : organizationno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.status
     *
     * @return the value of file_org.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.status
     *
     * @param status the value for file_org.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.creator
     *
     * @return the value of file_org.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.creator
     *
     * @param creator the value for file_org.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.createtime
     *
     * @return the value of file_org.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.createtime
     *
     * @param createtime the value for file_org.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.modifier
     *
     * @return the value of file_org.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.modifier
     *
     * @param modifier the value for file_org.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.modifytime
     *
     * @return the value of file_org.modifytime
     *
     * @mbggenerated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.modifytime
     *
     * @param modifytime the value for file_org.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.DESC1
     *
     * @return the value of file_org.DESC1
     *
     * @mbggenerated
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.DESC1
     *
     * @param desc1 the value for file_org.DESC1
     *
     * @mbggenerated
     */
    public void setDesc1(String desc1) {
        this.desc1 = desc1 == null ? null : desc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.DESC2
     *
     * @return the value of file_org.DESC2
     *
     * @mbggenerated
     */
    public String getDesc2() {
        return desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.DESC2
     *
     * @param desc2 the value for file_org.DESC2
     *
     * @mbggenerated
     */
    public void setDesc2(String desc2) {
        this.desc2 = desc2 == null ? null : desc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.DESC3
     *
     * @return the value of file_org.DESC3
     *
     * @mbggenerated
     */
    public String getDesc3() {
        return desc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.DESC3
     *
     * @param desc3 the value for file_org.DESC3
     *
     * @mbggenerated
     */
    public void setDesc3(String desc3) {
        this.desc3 = desc3 == null ? null : desc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_org.DESC4
     *
     * @return the value of file_org.DESC4
     *
     * @mbggenerated
     */
    public String getDesc4() {
        return desc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_org.DESC4
     *
     * @param desc4 the value for file_org.DESC4
     *
     * @mbggenerated
     */
    public void setDesc4(String desc4) {
        this.desc4 = desc4 == null ? null : desc4.trim();
    }

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}
    
    
}