package com.tianrui.service.admin.bean;

public class FileRoute {

    private String id;
    private String organizationname;
    private String organizationid;
    private String routename;
    private String status;//（0-可用；1-暂不可用；2-已删除）
    
    private String count;//被引用次数
    
    private String opositionid;
    private String oaddr;
    private String dpositionid;
    private String daddr;
    
    private String sendpersion;
    private String sendpersionphone;
    private String receivepersion;
    private String receivepersionphone;
    
    private Double distance;
    private String creator;
    private Long createtime;
    private String modifier;
    private Long modifytime;
    
    private Integer start;
    private Integer limit;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.ID
     *
     * @param id the value for file_route.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getCount() {
		return count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.organizationname
     *
     * @return the value of file_route.organizationname
     *
     * @mbggenerated
     */
    public String getOrganizationname() {
        return organizationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.organizationname
     *
     * @param organizationname the value for file_route.organizationname
     *
     * @mbggenerated
     */
    public void setOrganizationname(String organizationname) {
        this.organizationname = organizationname == null ? null : organizationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.organizationid
     *
     * @return the value of file_route.organizationid
     *
     * @mbggenerated
     */
    public String getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.organizationid
     *
     * @param organizationid the value for file_route.organizationid
     *
     * @mbggenerated
     */
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid == null ? null : organizationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.routename
     *
     * @return the value of file_route.routename
     *
     * @mbggenerated
     */
    public String getRoutename() {
        return routename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.routename
     *
     * @param routename the value for file_route.routename
     *
     * @mbggenerated
     */
    public void setRoutename(String routename) {
        this.routename = routename == null ? null : routename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.status
     *
     * @return the value of file_route.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.status
     *
     * @param status the value for file_route.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.oPositionId
     *
     * @return the value of file_route.oPositionId
     *
     * @mbggenerated
     */
    public String getOpositionid() {
        return opositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.oPositionId
     *
     * @param opositionid the value for file_route.oPositionId
     *
     * @mbggenerated
     */
    public void setOpositionid(String opositionid) {
        this.opositionid = opositionid == null ? null : opositionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.oAddr
     *
     * @return the value of file_route.oAddr
     *
     * @mbggenerated
     */
    public String getOaddr() {
        return oaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.oAddr
     *
     * @param oaddr the value for file_route.oAddr
     *
     * @mbggenerated
     */
    public void setOaddr(String oaddr) {
        this.oaddr = oaddr == null ? null : oaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.dPositionId
     *
     * @return the value of file_route.dPositionId
     *
     * @mbggenerated
     */
    public String getDpositionid() {
        return dpositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.dPositionId
     *
     * @param dpositionid the value for file_route.dPositionId
     *
     * @mbggenerated
     */
    public void setDpositionid(String dpositionid) {
        this.dpositionid = dpositionid == null ? null : dpositionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.dAddr
     *
     * @return the value of file_route.dAddr
     *
     * @mbggenerated
     */
    public String getDaddr() {
        return daddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.dAddr
     *
     * @param daddr the value for file_route.dAddr
     *
     * @mbggenerated
     */
    public void setDaddr(String daddr) {
        this.daddr = daddr == null ? null : daddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.sendPersion
     *
     * @return the value of file_route.sendPersion
     *
     * @mbggenerated
     */
    public String getSendpersion() {
        return sendpersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.sendPersion
     *
     * @param sendpersion the value for file_route.sendPersion
     *
     * @mbggenerated
     */
    public void setSendpersion(String sendpersion) {
        this.sendpersion = sendpersion == null ? null : sendpersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.sendPersionPhone
     *
     * @return the value of file_route.sendPersionPhone
     *
     * @mbggenerated
     */
    public String getSendpersionphone() {
        return sendpersionphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.sendPersionPhone
     *
     * @param sendpersionphone the value for file_route.sendPersionPhone
     *
     * @mbggenerated
     */
    public void setSendpersionphone(String sendpersionphone) {
        this.sendpersionphone = sendpersionphone == null ? null : sendpersionphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.receivePersion
     *
     * @return the value of file_route.receivePersion
     *
     * @mbggenerated
     */
    public String getReceivepersion() {
        return receivepersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.receivePersion
     *
     * @param receivepersion the value for file_route.receivePersion
     *
     * @mbggenerated
     */
    public void setReceivepersion(String receivepersion) {
        this.receivepersion = receivepersion == null ? null : receivepersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.receivePersionPhone
     *
     * @return the value of file_route.receivePersionPhone
     *
     * @mbggenerated
     */
    public String getReceivepersionphone() {
        return receivepersionphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.receivePersionPhone
     *
     * @param receivepersionphone the value for file_route.receivePersionPhone
     *
     * @mbggenerated
     */
    public void setReceivepersionphone(String receivepersionphone) {
        this.receivepersionphone = receivepersionphone == null ? null : receivepersionphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.distance
     *
     * @return the value of file_route.distance
     *
     * @mbggenerated
     */
    public Double getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.distance
     *
     * @param distance the value for file_route.distance
     *
     * @mbggenerated
     */
    public void setDistance(Double distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.creator
     *
     * @return the value of file_route.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.creator
     *
     * @param creator the value for file_route.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.createtime
     *
     * @return the value of file_route.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.createtime
     *
     * @param createtime the value for file_route.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.modifier
     *
     * @return the value of file_route.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.modifier
     *
     * @param modifier the value for file_route.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_route.modifytime
     *
     * @return the value of file_route.modifytime
     *
     * @mbggenerated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_route.modifytime
     *
     * @param modifytime the value for file_route.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}
    
}