package com.tianrui.service.admin.bean;

import com.tianrui.service.bean.IModel;
/**
 * 
 * @类描述：菜单类,通过调整数据库数据来调整菜单结构
 * @创建人：tank
 * @创建时间：2016年1月18日下午4:09:27
 *
 * @修改人：tank
 * @修改时间：2016年1月18日下午4:09:27
 * @修改备注：
 *
 */
public class Mainmenu implements IModel{
    /**
     * id
     * @mbggenerated
     */
    private Integer id;

    /**
     *  节点名
     * @mbggenerated
     */
    private String nodename;

    /**
     * 后台节点名，菜单显示名字，为空时菜单不显示
     * @mbggenerated
     */
    private String afternodename;

    /**
     * 创建时间  yyyy-MM-dd HH:mm:ss
     * @mbggenerated
     */
    private String createtime;

    /**
     *  父节点id
     * @mbggenerated
     */
    private Integer parentnodeid;

    /**
     * 前台url
     * @mbggenerated
     */
    private String fronturl;

    /**
     * 后台url
     */
    private String afterurl;

    /**
     * 子菜单显示顺序
     */
    private Integer order1;

    /**
     * @mbggenerated
     */
    private String desc1;

    /**
     *
     * @mbggenerated
     */
    private String desc2;

    /**
     *
     * @mbggenerated
     */
    private String desc3;

    /**
     *
     * @mbggenerated
     */
    private String desc4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.ID
     *
     * @return the value of trwuliu_mainmenu.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.ID
     *
     * @param id the value for trwuliu_mainmenu.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.nodeName
     *
     * @return the value of trwuliu_mainmenu.nodeName
     *
     * @mbggenerated
     */
    public String getNodename() {
        return nodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.nodeName
     *
     * @param nodename the value for trwuliu_mainmenu.nodeName
     *
     * @mbggenerated
     */
    public void setNodename(String nodename) {
        this.nodename = nodename == null ? null : nodename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.afterNodeName
     *
     * @return the value of trwuliu_mainmenu.afterNodeName
     *
     * @mbggenerated
     */
    public String getAfternodename() {
        return afternodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.afterNodeName
     *
     * @param afternodename the value for trwuliu_mainmenu.afterNodeName
     *
     * @mbggenerated
     */
    public void setAfternodename(String afternodename) {
        this.afternodename = afternodename == null ? null : afternodename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.CREATETIME
     *
     * @return the value of trwuliu_mainmenu.CREATETIME
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.CREATETIME
     *
     * @param createtime the value for trwuliu_mainmenu.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.parentNodeId
     *
     * @return the value of trwuliu_mainmenu.parentNodeId
     *
     * @mbggenerated
     */
    public Integer getParentnodeid() {
        return parentnodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.parentNodeId
     *
     * @param parentnodeid the value for trwuliu_mainmenu.parentNodeId
     *
     * @mbggenerated
     */
    public void setParentnodeid(Integer parentnodeid) {
        this.parentnodeid = parentnodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.frontUrl
     *
     * @return the value of trwuliu_mainmenu.frontUrl
     *
     * @mbggenerated
     */
    public String getFronturl() {
        return fronturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.frontUrl
     *
     * @param fronturl the value for trwuliu_mainmenu.frontUrl
     *
     * @mbggenerated
     */
    public void setFronturl(String fronturl) {
        this.fronturl = fronturl == null ? null : fronturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.afterUrl
     *
     * @return the value of trwuliu_mainmenu.afterUrl
     *
     * @mbggenerated
     */
    public String getAfterurl() {
        return afterurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.afterUrl
     *
     * @param afterurl the value for trwuliu_mainmenu.afterUrl
     *
     * @mbggenerated
     */
    public void setAfterurl(String afterurl) {
        this.afterurl = afterurl == null ? null : afterurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.order_1
     *
     * @return the value of trwuliu_mainmenu.order_1
     *
     * @mbggenerated
     */
    public Integer getOrder1() {
        return order1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.order_1
     *
     * @param order1 the value for trwuliu_mainmenu.order_1
     *
     * @mbggenerated
     */
    public void setOrder1(Integer order1) {
        this.order1 = order1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.DESC1
     *
     * @return the value of trwuliu_mainmenu.DESC1
     *
     * @mbggenerated
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.DESC1
     *
     * @param desc1 the value for trwuliu_mainmenu.DESC1
     *
     * @mbggenerated
     */
    public void setDesc1(String desc1) {
        this.desc1 = desc1 == null ? null : desc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.DESC2
     *
     * @return the value of trwuliu_mainmenu.DESC2
     *
     * @mbggenerated
     */
    public String getDesc2() {
        return desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.DESC2
     *
     * @param desc2 the value for trwuliu_mainmenu.DESC2
     *
     * @mbggenerated
     */
    public void setDesc2(String desc2) {
        this.desc2 = desc2 == null ? null : desc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.DESC3
     *
     * @return the value of trwuliu_mainmenu.DESC3
     *
     * @mbggenerated
     */
    public String getDesc3() {
        return desc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.DESC3
     *
     * @param desc3 the value for trwuliu_mainmenu.DESC3
     *
     * @mbggenerated
     */
    public void setDesc3(String desc3) {
        this.desc3 = desc3 == null ? null : desc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_mainmenu.DESC4
     *
     * @return the value of trwuliu_mainmenu.DESC4
     *
     * @mbggenerated
     */
    public String getDesc4() {
        return desc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_mainmenu.DESC4
     *
     * @param desc4 the value for trwuliu_mainmenu.DESC4
     *
     * @mbggenerated
     */
    public void setDesc4(String desc4) {
        this.desc4 = desc4 == null ? null : desc4.trim();
    }
}