package com.tianrui.service.admin.bean;

import com.tianrui.service.bean.IModel;
/**
 * @字段：serialVersionUID
 * @功能描述：
 * @创建人：tank
 * @创建时间：2016年4月12日下午1:14:43
 */
public class RoleMenu implements IModel{
    /**
     * id
     * @mbggenerated
     */
    private Integer id;

    /**
     * 菜单
     */
    private Integer menuidR;

    /**
     * 角色
     */
    private Integer roleidM;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_Role_Menu.ID
     *
     * @return the value of trwuliu_Role_Menu.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_Role_Menu.ID
     *
     * @param id the value for trwuliu_Role_Menu.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_Role_Menu.MENUID_R
     *
     * @return the value of trwuliu_Role_Menu.MENUID_R
     *
     * @mbggenerated
     */
    public Integer getMenuidR() {
        return menuidR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_Role_Menu.MENUID_R
     *
     * @param menuidR the value for trwuliu_Role_Menu.MENUID_R
     *
     * @mbggenerated
     */
    public void setMenuidR(Integer menuidR) {
        this.menuidR = menuidR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_Role_Menu.ROLEID_M
     *
     * @return the value of trwuliu_Role_Menu.ROLEID_M
     *
     * @mbggenerated
     */
    public Integer getRoleidM() {
        return roleidM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_Role_Menu.ROLEID_M
     *
     * @param roleidM the value for trwuliu_Role_Menu.ROLEID_M
     *
     * @mbggenerated
     */
    public void setRoleidM(Integer roleidM) {
        this.roleidM = roleidM;
    }
}