package com.tianrui.service.admin.bean;

import com.tianrui.service.bean.IModel;
/**
 * 
 * @类描述：用户重要操作日志类 
 * @创建人：tank
 * @创建时间：2016年1月18日下午4:25:14
 *
 * @修改人：tank
 * @修改时间：2016年1月18日下午4:25:14
 * @修改备注：
 *
 */
public class Systemlog implements IModel{
    /**
     * 主键
     */
    private Integer id;

    /**
     * 操作时间  yyyy-MM-dd HH:mm:ss
     */
    private String createtime;

    /**
     * 操作描述
     */
    private String description;

    /**
   * 操作类型
     */
    private String logtype;

    /**
     */
    private String desc1;

    /**
     */
    private String desc2;

    /**
     */
    private String desc3;

    /**
     */
    private String desc4;

    /**
     * 用户
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_systemlog.ID
     *
     * @return the value of trwuliu_systemlog.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_systemlog.ID
     *
     * @param id the value for trwuliu_systemlog.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_systemlog.CREATETIME
     *
     * @return the value of trwuliu_systemlog.CREATETIME
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_systemlog.CREATETIME
     *
     * @param createtime the value for trwuliu_systemlog.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_systemlog.description
     *
     * @return the value of trwuliu_systemlog.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_systemlog.description
     *
     * @param description the value for trwuliu_systemlog.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_systemlog.logType
     *
     * @return the value of trwuliu_systemlog.logType
     *
     * @mbggenerated
     */
    public String getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_systemlog.logType
     *
     * @param logtype the value for trwuliu_systemlog.logType
     *
     * @mbggenerated
     */
    public void setLogtype(String logtype) {
        this.logtype = logtype == null ? null : logtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_systemlog.DESC1
     *
     * @return the value of trwuliu_systemlog.DESC1
     *
     * @mbggenerated
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_systemlog.DESC1
     *
     * @param desc1 the value for trwuliu_systemlog.DESC1
     *
     * @mbggenerated
     */
    public void setDesc1(String desc1) {
        this.desc1 = desc1 == null ? null : desc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_systemlog.DESC2
     *
     * @return the value of trwuliu_systemlog.DESC2
     *
     * @mbggenerated
     */
    public String getDesc2() {
        return desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_systemlog.DESC2
     *
     * @param desc2 the value for trwuliu_systemlog.DESC2
     *
     * @mbggenerated
     */
    public void setDesc2(String desc2) {
        this.desc2 = desc2 == null ? null : desc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_systemlog.DESC3
     *
     * @return the value of trwuliu_systemlog.DESC3
     *
     * @mbggenerated
     */
    public String getDesc3() {
        return desc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_systemlog.DESC3
     *
     * @param desc3 the value for trwuliu_systemlog.DESC3
     *
     * @mbggenerated
     */
    public void setDesc3(String desc3) {
        this.desc3 = desc3 == null ? null : desc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_systemlog.DESC4
     *
     * @return the value of trwuliu_systemlog.DESC4
     *
     * @mbggenerated
     */
    public String getDesc4() {
        return desc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_systemlog.DESC4
     *
     * @param desc4 the value for trwuliu_systemlog.DESC4
     *
     * @mbggenerated
     */
    public void setDesc4(String desc4) {
        this.desc4 = desc4 == null ? null : desc4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_systemlog.USERID
     *
     * @return the value of trwuliu_systemlog.USERID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_systemlog.USERID
     *
     * @param userid the value for trwuliu_systemlog.USERID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}