package com.tianrui.service.admin.bean;

import com.tianrui.service.bean.IModel;
/**
 * 
 * @类描述：用户和角色关系
 * @创建人：tank
 * @创建时间：2016年4月12日下午1:35:54
 *
 * @修改人：tank
 * @修改时间：2016年4月12日下午1:35:54
 * @修改备注：
 *
 */
public class UserRole implements IModel{
    /**
     * id
     */
    private Integer id;

    /**
     * 用户
     */
    private Integer userid;

    /**
     * 角色
     */
    private Integer roleidU;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_User_Role.ID
     *
     * @return the value of trwuliu_User_Role.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_User_Role.ID
     *
     * @param id the value for trwuliu_User_Role.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_User_Role.USERID
     *
     * @return the value of trwuliu_User_Role.USERID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_User_Role.USERID
     *
     * @param userid the value for trwuliu_User_Role.USERID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_User_Role.ROLEID_U
     *
     * @return the value of trwuliu_User_Role.ROLEID_U
     *
     * @mbggenerated
     */
    public Integer getRoleidU() {
        return roleidU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_User_Role.ROLEID_U
     *
     * @param roleidU the value for trwuliu_User_Role.ROLEID_U
     *
     * @mbggenerated
     */
    public void setRoleidU(Integer roleidU) {
        this.roleidU = roleidU;
    }
}