package com.tianrui.service.admin.bean;

import com.tianrui.service.bean.IModel;
/**
 * 
 * @类描述：系统用户
 * @创建人：tank
 * @创建时间：2016年1月18日下午4:17:02
 *
 * @修改人：tank
 * @修改时间：2016年1月18日下午4:17:02
 * @修改备注：
 *
 */
public class Users implements IModel{
	private static final long serialVersionUID = -2339847197298728504L;

	/**
	 * 主键
	 */
    private Integer id;

    /**
	 * 登陆账号，唯一不可重复
	 */
    private String account;

    /**
	 * 登陆密码
	 */
    private String password;

    /**
	 * 创建时间  yyyy-MM-dd HH:mm:ss
	 */
    private String createtime;

    /**
	 * 登陆次数
	 */
    private Integer logincount;

    /**
	 * 购买总条数
	 */
    private Integer totalpurchases;

    /**
	 * 已使用总数
	 */
    private Integer usedtotal;

    /**
	 * 用户姓名
	 */
    private String usertype;

    /**
	 * 手机号码
	 */
    private String telnum;

    /**
	 * 状态
	 */
    private Integer status;
    /**
     * 组织id
     */
    private String orgid;
    /**
     * 组织姓名
     */
    private String orgname;
    /**
     *
     */
    private String desc1;

    /**
     * 
     */
    private String desc2;

    /**
     * 
     */
    private String desc3;

    /**
     */
    private String desc4;
    
    
    private Integer start;
    private Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.ID
     *
     * @return the value of trwuliu_users.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.ID
     *
     * @param id the value for trwuliu_users.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public String getOrgid() {
		return orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getOrgname() {
		return orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.ACCOUNT
     *
     * @return the value of trwuliu_users.ACCOUNT
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.ACCOUNT
     *
     * @param account the value for trwuliu_users.ACCOUNT
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.PASSWORD
     *
     * @return the value of trwuliu_users.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.PASSWORD
     *
     * @param password the value for trwuliu_users.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.CREATETIME
     *
     * @return the value of trwuliu_users.CREATETIME
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.CREATETIME
     *
     * @param createtime the value for trwuliu_users.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.LOGINCOUNT
     *
     * @return the value of trwuliu_users.LOGINCOUNT
     *
     * @mbggenerated
     */
    public Integer getLogincount() {
        return logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.LOGINCOUNT
     *
     * @param logincount the value for trwuliu_users.LOGINCOUNT
     *
     * @mbggenerated
     */
    public void setLogincount(Integer logincount) {
        this.logincount = logincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.totalPurchases
     *
     * @return the value of trwuliu_users.totalPurchases
     *
     * @mbggenerated
     */
    public Integer getTotalpurchases() {
        return totalpurchases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.totalPurchases
     *
     * @param totalpurchases the value for trwuliu_users.totalPurchases
     *
     * @mbggenerated
     */
    public void setTotalpurchases(Integer totalpurchases) {
        this.totalpurchases = totalpurchases;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.usedTotal
     *
     * @return the value of trwuliu_users.usedTotal
     *
     * @mbggenerated
     */
    public Integer getUsedtotal() {
        return usedtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.usedTotal
     *
     * @param usedtotal the value for trwuliu_users.usedTotal
     *
     * @mbggenerated
     */
    public void setUsedtotal(Integer usedtotal) {
        this.usedtotal = usedtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.USERTYPE
     *
     * @return the value of trwuliu_users.USERTYPE
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.USERTYPE
     *
     * @param usertype the value for trwuliu_users.USERTYPE
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.telnum
     *
     * @return the value of trwuliu_users.telnum
     *
     * @mbggenerated
     */
    public String getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.telnum
     *
     * @param telnum the value for trwuliu_users.telnum
     *
     * @mbggenerated
     */
    public void setTelnum(String telnum) {
        this.telnum = telnum == null ? null : telnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.STATUS
     *
     * @return the value of trwuliu_users.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.STATUS
     *
     * @param status the value for trwuliu_users.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.DESC1
     *
     * @return the value of trwuliu_users.DESC1
     *
     * @mbggenerated
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.DESC1
     *
     * @param desc1 the value for trwuliu_users.DESC1
     *
     * @mbggenerated
     */
    public void setDesc1(String desc1) {
        this.desc1 = desc1 == null ? null : desc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.DESC2
     *
     * @return the value of trwuliu_users.DESC2
     *
     * @mbggenerated
     */
    public String getDesc2() {
        return desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.DESC2
     *
     * @param desc2 the value for trwuliu_users.DESC2
     *
     * @mbggenerated
     */
    public void setDesc2(String desc2) {
        this.desc2 = desc2 == null ? null : desc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.DESC3
     *
     * @return the value of trwuliu_users.DESC3
     *
     * @mbggenerated
     */
    public String getDesc3() {
        return desc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.DESC3
     *
     * @param desc3 the value for trwuliu_users.DESC3
     *
     * @mbggenerated
     */
    public void setDesc3(String desc3) {
        this.desc3 = desc3 == null ? null : desc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_users.DESC4
     *
     * @return the value of trwuliu_users.DESC4
     *
     * @mbggenerated
     */
    public String getDesc4() {
        return desc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_users.DESC4
     *
     * @param desc4 the value for trwuliu_users.DESC4
     *
     * @mbggenerated
     */
    public void setDesc4(String desc4) {
        this.desc4 = desc4 == null ? null : desc4.trim();
    }

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}


    
}