package com.tianrui.service.mapper;

import com.tianrui.service.bean.FileIndex;

public interface FileIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_file_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_file_index
     *
     * @mbggenerated
     */
    int insert(FileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_file_index
     *
     * @mbggenerated
     */
    int insertSelective(FileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_file_index
     *
     * @mbggenerated
     */
    FileIndex selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_file_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_file_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileIndex record);
}