package com.tianrui.service.mapper;

import com.tianrui.service.bean.FreighrMember;

public interface FreighrMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_freighr_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_freighr_member
     *
     * @mbggenerated
     */
    int insert(FreighrMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_freighr_member
     *
     * @mbggenerated
     */
    int insertSelective(FreighrMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_freighr_member
     *
     * @mbggenerated
     */
    FreighrMember selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_freighr_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FreighrMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_freighr_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FreighrMember record);
}