package com.tianrui.service.mapper;

import java.util.List;

import com.tianrui.service.bean.MemberPosition;

public interface MemberPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_position
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_position
     *
     * @mbggenerated
     */
    int insert(MemberPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_position
     *
     * @mbggenerated
     */
    int insertSelective(MemberPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_position
     *
     * @mbggenerated
     */
    MemberPosition selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberPosition record);
    
    List<MemberPosition> findWithCondition(MemberPosition record);
    MemberPosition findWithMid(String mId);
}