package com.tianrui.service.mapper;

import java.util.List;

import com.tianrui.service.bean.MemberVehicle;
import com.tianrui.service.bean.VehicleAndDriver;

public interface MemberVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_vehicle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_vehicle
     *
     * @mbggenerated
     */
    int insert(MemberVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_vehicle
     *
     * @mbggenerated
     */
    int insertSelective(MemberVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_vehicle
     *
     * @mbggenerated
     */
    MemberVehicle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberVehicle record);
    
    /**
     * 根据主键进行我的车辆信息查询
     * <p>
     * @param id  主键
     * @return
     * <p>
     * @author guyuke
     * @time 2016年6月06日 上午11:14:00
     */
    List<MemberVehicle> selectMyVehicleById(String id);
    
    /**
     * 根据条件进行我的车辆信息查询
     * <p>
     * @param argCondition
     * @return
     * <p>
     * @author guyuke
     * @time 2016年6月06日 上午11:14:00
     */
    List<MemberVehicle> selectMyVehicleByCondition(MemberVehicle argCondition);
    
    /**
     * 根据条件进行我的车辆信息数据总量查询
     * <p>
     * @param argCondition
     * @return
     * <p>
     * @author guyuke
     * @time 2016年6月06日 上午11:14:00
     */
    long selectCountByCondition(MemberVehicle argCondition);
    
    /**
     * 根据条件进行车辆司机联合信息查询
     * <p>
     * @param argCondition
     * @return
     * <p>
     * @author guyuke
     * @time 2016年6月06日 上午11:14:00
     */
    List<VehicleAndDriver> selectVehicleAndDriverByCondition(VehicleAndDriver argCondition);
    /**
     * 根据条件进行车辆司机联合信息查询总数
     * <p>
     * @param argCondition
     * @return
     * <p>
     * @author guyuke
     * @time 2016年6月06日 上午11:14:00
     */
    long selectVehicleAndDriverBycount(VehicleAndDriver argCondition);
    /**
     * 根据vehicleIds进行车辆司机联合信息查询
     * <p>
     * @param vehicleIds
     * @return
     * <p>
     * @author zhanggh
     * @time 2016年7月28日 上午11:33:00
     */
    List<MemberVehicle> selectVehicleByIds(List<String> vehicleIds);
}