package com.tianrui.service.mapper;

import java.util.List;

import com.tianrui.service.bean.MemberOwner;

public interface MemberOwnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_owner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_owner
     *
     * @mbggenerated
     */
    int insert(MemberOwner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_owner
     *
     * @mbggenerated
     */
    int insertSelective(MemberOwner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_owner
     *
     * @mbggenerated
     */
    MemberOwner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_owner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MemberOwner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_member_owner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MemberOwner record);
    
    /**
     * 根据条件进行我的车主信息查询
     * <p>
     * @param argCondition
     * @return
     * <p>
     * @author guyuke
     * @time 2016年6月06日 上午11:14:00
     */
    List<MemberOwner> selectMyVehiOwnerByCondition(MemberOwner argCondition);
    
    /**
     * 根据条件进行我的车主信息数据总量查询
     * <p>
     * @param argCondition
     * @return
     * <p>
     * @author guyuke
     * @time 2016年6月06日 上午11:14:00
     */
    long selectCountByCondition(MemberOwner argCondition);
}