package com.tianrui.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.tianrui.service.bean.Plan;

public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_plan
     *
     * @mbggenerated
     */
    int insert(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_plan
     *
     * @mbggenerated
     */
    int insertSelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_plan
     *
     * @mbggenerated
     */
    Plan selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Plan record);
    
    List<Plan> selectByCondition(Plan record);
    
    long countByCondition(Plan record);

	List<Plan> selectByEndTime(Long st);
	
	List<Plan> selectAppointByParams(String pid);
	
	Plan selectRootPlanByPlanId(String planid);

	List<Plan> selectChildPlan(@Param("planCode")String planCode, @Param("pid")String pid);
}