package com.tianrui.service.mapper;

import java.util.List;

import com.tianrui.api.resp.front.member.MemberInfoRecordResp;
import com.tianrui.service.bean.SystemMemberInfoRecord;

public interface SystemMemberInfoRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_info_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_info_record
     *
     * @mbggenerated
     */
    int insert(SystemMemberInfoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_info_record
     *
     * @mbggenerated
     */
    int insertSelective(SystemMemberInfoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_info_record
     *
     * @mbggenerated
     */
    SystemMemberInfoRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_info_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemMemberInfoRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_info_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemMemberInfoRecord record);
    
    /**
     * 
     * @描述:会员认证信息查询
     * @param record
     * @return
     * @返回类型 List<MemberInfoRecord>
     * @创建人 lsj
     * @创建时间 2016年6月22日上午10:04:56
     */
    List<SystemMemberInfoRecord> selectByRecordEntity(SystemMemberInfoRecord record);
}