package com.tianrui.service.mapper;

import java.util.List;

import com.tianrui.service.admin.bean.Members;
import com.tianrui.service.bean.MemberFind;
import com.tianrui.service.bean.SystemMember;

public interface SystemMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int insert(SystemMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int insertSelective(SystemMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    SystemMember selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemMember record);
     
    List<SystemMember> selectByCondition(SystemMember record);
    /**
     * 后台会员查询
     */
    List<Members> findsMemberList(MemberFind find);
    /**
     * 后台会员查询查询条数
     */
    long findsMemberListCount(MemberFind find);
    
    Members findsMemberbyId(String id);
    
    Members bindDriver(String phone);
    /**
     * 运力管理联合查询
     * @param id
     * @return
     */
	Members findByMemberId(String id);
	List<Members> findByMemberIds(String id);
	
	//司机用户查询审核通过/不通过
	 Long driverByNum(MemberFind ms);
	 //用户
	Long  userByNum(MemberFind ms);
    
}