package com.tianrui.service.mapper;

import com.tianrui.service.bean.Vehickle;

public interface VehickleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_vehicle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_vehicle
     *
     * @mbggenerated
     */
    int insert(Vehickle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_vehicle
     *
     * @mbggenerated
     */
    int insertSelective(Vehickle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_vehicle
     *
     * @mbggenerated
     */
    Vehickle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Vehickle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliu_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Vehickle record);
}