package com.tianrui.service.bean;

import java.util.Date;

public class DataDict implements IModel{
    /**
     * 主键id
     * @mbggenerated
     */
    private String id;

    /**
     * 父菜单编号
     * @mbggenerated
     */
    private String subcode;

    /**
     *	父菜单名称
     * @mbggenerated
     */
    private String subname;

    /**
     *	子菜单编号
     * @mbggenerated
     */
    private String itemcode;

    /**
     * 子菜单名称
     * @mbggenerated
     */
    private String itemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_dataDict.timestamp
     *
     * @mbggenerated
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_dataDict.ID
     *
     * @return the value of wuliu_dataDict.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_dataDict.ID
     *
     * @param id the value for wuliu_dataDict.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_dataDict.subCode
     *
     * @return the value of wuliu_dataDict.subCode
     *
     * @mbggenerated
     */
    public String getSubcode() {
        return subcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_dataDict.subCode
     *
     * @param subcode the value for wuliu_dataDict.subCode
     *
     * @mbggenerated
     */
    public void setSubcode(String subcode) {
        this.subcode = subcode == null ? null : subcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_dataDict.subName
     *
     * @return the value of wuliu_dataDict.subName
     *
     * @mbggenerated
     */
    public String getSubname() {
        return subname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_dataDict.subName
     *
     * @param subname the value for wuliu_dataDict.subName
     *
     * @mbggenerated
     */
    public void setSubname(String subname) {
        this.subname = subname == null ? null : subname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_dataDict.itemCode
     *
     * @return the value of wuliu_dataDict.itemCode
     *
     * @mbggenerated
     */
    public String getItemcode() {
        return itemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_dataDict.itemCode
     *
     * @param itemcode the value for wuliu_dataDict.itemCode
     *
     * @mbggenerated
     */
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode == null ? null : itemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_dataDict.itemName
     *
     * @return the value of wuliu_dataDict.itemName
     *
     * @mbggenerated
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_dataDict.itemName
     *
     * @param itemname the value for wuliu_dataDict.itemName
     *
     * @mbggenerated
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_dataDict.timestamp
     *
     * @return the value of wuliu_dataDict.timestamp
     *
     * @mbggenerated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_dataDict.timestamp
     *
     * @param timestamp the value for wuliu_dataDict.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}