package com.tianrui.service.bean;

public class FileIndex  implements IModel{
 
	private static final long serialVersionUID = 8863034302276253447L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.file_path
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.file_title
     *
     * @mbggenerated
     */
    private String fileTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.md5
     *
     * @mbggenerated
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.task_id
     *
     * @mbggenerated
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.ctime
     *
     * @mbggenerated
     */
    private String ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.author_name
     *
     * @mbggenerated
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.crc32
     *
     * @mbggenerated
     */
    private String crc32;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.thumbnailsPath
     *
     * @mbggenerated
     */
    private String thumbnailspath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.file_size
     *
     * @mbggenerated
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.author_id
     *
     * @mbggenerated
     */
    private Long authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.module_type
     *
     * @mbggenerated
     */
    private Integer moduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trwuliu_file_index.fileType
     *
     * @mbggenerated
     */
    private Integer filetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.id
     *
     * @return the value of trwuliu_file_index.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.id
     *
     * @param id the value for trwuliu_file_index.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.file_path
     *
     * @return the value of trwuliu_file_index.file_path
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.file_path
     *
     * @param filePath the value for trwuliu_file_index.file_path
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.file_title
     *
     * @return the value of trwuliu_file_index.file_title
     *
     * @mbggenerated
     */
    public String getFileTitle() {
        return fileTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.file_title
     *
     * @param fileTitle the value for trwuliu_file_index.file_title
     *
     * @mbggenerated
     */
    public void setFileTitle(String fileTitle) {
        this.fileTitle = fileTitle == null ? null : fileTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.md5
     *
     * @return the value of trwuliu_file_index.md5
     *
     * @mbggenerated
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.md5
     *
     * @param md5 the value for trwuliu_file_index.md5
     *
     * @mbggenerated
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.task_id
     *
     * @return the value of trwuliu_file_index.task_id
     *
     * @mbggenerated
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.task_id
     *
     * @param taskId the value for trwuliu_file_index.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.ctime
     *
     * @return the value of trwuliu_file_index.ctime
     *
     * @mbggenerated
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.ctime
     *
     * @param ctime the value for trwuliu_file_index.ctime
     *
     * @mbggenerated
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.author_name
     *
     * @return the value of trwuliu_file_index.author_name
     *
     * @mbggenerated
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.author_name
     *
     * @param authorName the value for trwuliu_file_index.author_name
     *
     * @mbggenerated
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.crc32
     *
     * @return the value of trwuliu_file_index.crc32
     *
     * @mbggenerated
     */
    public String getCrc32() {
        return crc32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.crc32
     *
     * @param crc32 the value for trwuliu_file_index.crc32
     *
     * @mbggenerated
     */
    public void setCrc32(String crc32) {
        this.crc32 = crc32 == null ? null : crc32.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.thumbnailsPath
     *
     * @return the value of trwuliu_file_index.thumbnailsPath
     *
     * @mbggenerated
     */
    public String getThumbnailspath() {
        return thumbnailspath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.thumbnailsPath
     *
     * @param thumbnailspath the value for trwuliu_file_index.thumbnailsPath
     *
     * @mbggenerated
     */
    public void setThumbnailspath(String thumbnailspath) {
        this.thumbnailspath = thumbnailspath == null ? null : thumbnailspath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.file_size
     *
     * @return the value of trwuliu_file_index.file_size
     *
     * @mbggenerated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.file_size
     *
     * @param fileSize the value for trwuliu_file_index.file_size
     *
     * @mbggenerated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.status
     *
     * @return the value of trwuliu_file_index.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.status
     *
     * @param status the value for trwuliu_file_index.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.author_id
     *
     * @return the value of trwuliu_file_index.author_id
     *
     * @mbggenerated
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.author_id
     *
     * @param authorId the value for trwuliu_file_index.author_id
     *
     * @mbggenerated
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.module_type
     *
     * @return the value of trwuliu_file_index.module_type
     *
     * @mbggenerated
     */
    public Integer getModuleType() {
        return moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.module_type
     *
     * @param moduleType the value for trwuliu_file_index.module_type
     *
     * @mbggenerated
     */
    public void setModuleType(Integer moduleType) {
        this.moduleType = moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trwuliu_file_index.fileType
     *
     * @return the value of trwuliu_file_index.fileType
     *
     * @mbggenerated
     */
    public Integer getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trwuliu_file_index.fileType
     *
     * @param filetype the value for trwuliu_file_index.fileType
     *
     * @mbggenerated
     */
    public void setFiletype(Integer filetype) {
        this.filetype = filetype;
    }
}