package com.tianrui.service.bean;

public class FreighrMember implements IModel{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_freighr_member.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_freighr_member.memberid
     *
     * @mbggenerated
     */
    private String memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_freighr_member.freightid
     *
     * @mbggenerated
     */
    private String freightid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_freighr_member.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_freighr_member.createtime
     *
     * @mbggenerated
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_freighr_member.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_freighr_member.remarkName
     *
     * @mbggenerated
     */
    private String remarkname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_freighr_member.id
     *
     * @return the value of wuliu_freighr_member.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_freighr_member.id
     *
     * @param id the value for wuliu_freighr_member.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_freighr_member.memberid
     *
     * @return the value of wuliu_freighr_member.memberid
     *
     * @mbggenerated
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_freighr_member.memberid
     *
     * @param memberid the value for wuliu_freighr_member.memberid
     *
     * @mbggenerated
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_freighr_member.freightid
     *
     * @return the value of wuliu_freighr_member.freightid
     *
     * @mbggenerated
     */
    public String getFreightid() {
        return freightid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_freighr_member.freightid
     *
     * @param freightid the value for wuliu_freighr_member.freightid
     *
     * @mbggenerated
     */
    public void setFreightid(String freightid) {
        this.freightid = freightid == null ? null : freightid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_freighr_member.creator
     *
     * @return the value of wuliu_freighr_member.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_freighr_member.creator
     *
     * @param creator the value for wuliu_freighr_member.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_freighr_member.createtime
     *
     * @return the value of wuliu_freighr_member.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_freighr_member.createtime
     *
     * @param createtime the value for wuliu_freighr_member.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_freighr_member.userName
     *
     * @return the value of wuliu_freighr_member.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_freighr_member.userName
     *
     * @param username the value for wuliu_freighr_member.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_freighr_member.remarkName
     *
     * @return the value of wuliu_freighr_member.remarkName
     *
     * @mbggenerated
     */
    public String getRemarkname() {
        return remarkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_freighr_member.remarkName
     *
     * @param remarkname the value for wuliu_freighr_member.remarkName
     *
     * @mbggenerated
     */
    public void setRemarkname(String remarkname) {
        this.remarkname = remarkname == null ? null : remarkname.trim();
    }
}