package com.tianrui.service.bean;

public class Member  implements IModel{
  
	private static final long serialVersionUID = -4535315058213562100L;

	/**
     *ID
     * @mbggenerated
     */
    private String id;

    /**
     * 注册手机号（登录账号1）
     * @mbggenerated
     */
    private String cellphone;

    /**
     * 登录名称（登录账号2）
     * @mbggenerated
     */
    private String loginname;

    /**
     * 关联QQ号（登录账号3）
     * @mbggenerated
     */
    private String qqnumber;

    /**
     * 推荐人
	 * 推荐人手机号
     * @mbggenerated
     */
    private String referrer;

    /**
     * 密码
     * @mbggenerated
     */
    private String password;

    /**
     * 平台昵称
     * @mbggenerated
     */
    private String username;
    /**
     * 性别 1男，2女
     */
    private String sex;
    /**
     * 联系手机(认证手机)-密文
     * @mbggenerated
     */
    private String mobile;

    /**
     * // 联系手机(明文)
     * @mbggenerated
     */
    private String phone;

    /**
     *  会员状态 0-失效,1-正常
     * @mbggenerated
     */
    private String status;

    /**
     * 1：企业用户，2：  个人用户 
     * @mbggenerated
     */
    private String usertype;

    /**
     * 审核不通过类型
     * @mbggenerated
     */
    private String rejecttype;

    /**
     * 审核不通过具体原因
     * @mbggenerated
     */
    private String rejectreason;

    /**
     * 注册时间
     * @mbggenerated
     */
    private String registtime;

    /**
     * 提交认证时间
     * @mbggenerated
     */
    private String submitdate;

    /**
     * 最后登录时间
     * @mbggenerated
     */
    private String lasttime;

    /**
     * 头像路径
     * @mbggenerated
     */
    private String avatarspath;

    /**
     * 上次登录手机型号
     * @mbggenerated
     */
    private String phonetype;

    /**
     * 上次登录设备编号
     * @mbggenerated
     */
    private String channeid;

    /**
     * 手机标示
     * @mbggenerated
     */
    private String imei;

    /**
     * 积分
     * @mbggenerated
     */
    private String point;

    /**
     * 微信唯一标示
     * @mbggenerated
     */
    private String openid;

    /**
     * 微信是否绑定
	 * 0-绑定，1-未绑定
     * @mbggenerated
     */
    private String wxtype;

    /**
     * 用户等级
	 * 0-普通会员，1-审核中会员，2-认证会员，3-诚信会员
     * @mbggenerated
     */
    private String userlvl;

    /**
     * 密码强度（1：弱，2：中，3：强）
     * @mbggenerated
     */
    private Short pwdstrength;

    /**
     * 用户状态：0：未认证， 1：认证通过 ，2：认证中，3：认证失败   
     * @mbggenerated
     */
    private Short percheckstatus;

    /**
     * 用户来源 0:注册 1：系统导入或者内部添加 
     * @mbggenerated
     */
    private Short sourcetype;

    /**
     * 0：认证会员   1：司机   2：车主  3：司机车主
     */
    private String desc1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_member.DESC2
     *
     * @mbggenerated
     */
    private String desc2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_member.DESC3
     *
     * @mbggenerated
     */
    private String desc3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_member.DESC4
     *
     * @mbggenerated
     */
    private String desc4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.ID
     *
     * @return the value of wuliu_member.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.ID
     *
     * @param id the value for wuliu_member.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.cellPhone
     *
     * @return the value of wuliu_member.cellPhone
     *
     * @mbggenerated
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.cellPhone
     *
     * @param cellphone the value for wuliu_member.cellPhone
     *
     * @mbggenerated
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone == null ? null : cellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.loginName
     *
     * @return the value of wuliu_member.loginName
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.loginName
     *
     * @param loginname the value for wuliu_member.loginName
     *
     * @mbggenerated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.qqNUmber
     *
     * @return the value of wuliu_member.qqNUmber
     *
     * @mbggenerated
     */
    public String getQqnumber() {
        return qqnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.qqNUmber
     *
     * @param qqnumber the value for wuliu_member.qqNUmber
     *
     * @mbggenerated
     */
    public void setQqnumber(String qqnumber) {
        this.qqnumber = qqnumber == null ? null : qqnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.referrer
     *
     * @return the value of wuliu_member.referrer
     *
     * @mbggenerated
     */
    public String getReferrer() {
        return referrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.referrer
     *
     * @param referrer the value for wuliu_member.referrer
     *
     * @mbggenerated
     */
    public void setReferrer(String referrer) {
        this.referrer = referrer == null ? null : referrer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.passWord
     *
     * @return the value of wuliu_member.passWord
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.passWord
     *
     * @param password the value for wuliu_member.passWord
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.userName
     *
     * @return the value of wuliu_member.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.userName
     *
     * @param username the value for wuliu_member.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.mobile
     *
     * @return the value of wuliu_member.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.mobile
     *
     * @param mobile the value for wuliu_member.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.phone
     *
     * @return the value of wuliu_member.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.phone
     *
     * @param phone the value for wuliu_member.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.status
     *
     * @return the value of wuliu_member.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.status
     *
     * @param status the value for wuliu_member.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.userType
     *
     * @return the value of wuliu_member.userType
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.userType
     *
     * @param usertype the value for wuliu_member.userType
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.rejectType
     *
     * @return the value of wuliu_member.rejectType
     *
     * @mbggenerated
     */
    public String getRejecttype() {
        return rejecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.rejectType
     *
     * @param rejecttype the value for wuliu_member.rejectType
     *
     * @mbggenerated
     */
    public void setRejecttype(String rejecttype) {
        this.rejecttype = rejecttype == null ? null : rejecttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.rejectReason
     *
     * @return the value of wuliu_member.rejectReason
     *
     * @mbggenerated
     */
    public String getRejectreason() {
        return rejectreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.rejectReason
     *
     * @param rejectreason the value for wuliu_member.rejectReason
     *
     * @mbggenerated
     */
    public void setRejectreason(String rejectreason) {
        this.rejectreason = rejectreason == null ? null : rejectreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.registTime
     *
     * @return the value of wuliu_member.registTime
     *
     * @mbggenerated
     */
    public String getRegisttime() {
        return registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.registTime
     *
     * @param registtime the value for wuliu_member.registTime
     *
     * @mbggenerated
     */
    public void setRegisttime(String registtime) {
        this.registtime = registtime == null ? null : registtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.submitDate
     *
     * @return the value of wuliu_member.submitDate
     *
     * @mbggenerated
     */
    public String getSubmitdate() {
        return submitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.submitDate
     *
     * @param submitdate the value for wuliu_member.submitDate
     *
     * @mbggenerated
     */
    public void setSubmitdate(String submitdate) {
        this.submitdate = submitdate == null ? null : submitdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.lastTime
     *
     * @return the value of wuliu_member.lastTime
     *
     * @mbggenerated
     */
    public String getLasttime() {
        return lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.lastTime
     *
     * @param lasttime the value for wuliu_member.lastTime
     *
     * @mbggenerated
     */
    public void setLasttime(String lasttime) {
        this.lasttime = lasttime == null ? null : lasttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.avatarsPath
     *
     * @return the value of wuliu_member.avatarsPath
     *
     * @mbggenerated
     */
    public String getAvatarspath() {
        return avatarspath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.avatarsPath
     *
     * @param avatarspath the value for wuliu_member.avatarsPath
     *
     * @mbggenerated
     */
    public void setAvatarspath(String avatarspath) {
        this.avatarspath = avatarspath == null ? null : avatarspath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.phoneType
     *
     * @return the value of wuliu_member.phoneType
     *
     * @mbggenerated
     */
    public String getPhonetype() {
        return phonetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.phoneType
     *
     * @param phonetype the value for wuliu_member.phoneType
     *
     * @mbggenerated
     */
    public void setPhonetype(String phonetype) {
        this.phonetype = phonetype == null ? null : phonetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.channeId
     *
     * @return the value of wuliu_member.channeId
     *
     * @mbggenerated
     */
    public String getChanneid() {
        return channeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.channeId
     *
     * @param channeid the value for wuliu_member.channeId
     *
     * @mbggenerated
     */
    public void setChanneid(String channeid) {
        this.channeid = channeid == null ? null : channeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.imei
     *
     * @return the value of wuliu_member.imei
     *
     * @mbggenerated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.imei
     *
     * @param imei the value for wuliu_member.imei
     *
     * @mbggenerated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.point
     *
     * @return the value of wuliu_member.point
     *
     * @mbggenerated
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.point
     *
     * @param point the value for wuliu_member.point
     *
     * @mbggenerated
     */
    public void setPoint(String point) {
        this.point = point == null ? null : point.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.openId
     *
     * @return the value of wuliu_member.openId
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.openId
     *
     * @param openid the value for wuliu_member.openId
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.wxType
     *
     * @return the value of wuliu_member.wxType
     *
     * @mbggenerated
     */
    public String getWxtype() {
        return wxtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.wxType
     *
     * @param wxtype the value for wuliu_member.wxType
     *
     * @mbggenerated
     */
    public void setWxtype(String wxtype) {
        this.wxtype = wxtype == null ? null : wxtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.userLvl
     *
     * @return the value of wuliu_member.userLvl
     *
     * @mbggenerated
     */
    public String getUserlvl() {
        return userlvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.userLvl
     *
     * @param userlvl the value for wuliu_member.userLvl
     *
     * @mbggenerated
     */
    public void setUserlvl(String userlvl) {
        this.userlvl = userlvl == null ? null : userlvl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.pwdStrength
     *
     * @return the value of wuliu_member.pwdStrength
     *
     * @mbggenerated
     */
    public Short getPwdstrength() {
        return pwdstrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.pwdStrength
     *
     * @param pwdstrength the value for wuliu_member.pwdStrength
     *
     * @mbggenerated
     */
    public void setPwdstrength(Short pwdstrength) {
        this.pwdstrength = pwdstrength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.perCheckStatus
     *
     * @return the value of wuliu_member.perCheckStatus
     *
     * @mbggenerated
     */
    public Short getPercheckstatus() {
        return percheckstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.perCheckStatus
     *
     * @param percheckstatus the value for wuliu_member.perCheckStatus
     *
     * @mbggenerated
     */
    public void setPercheckstatus(Short percheckstatus) {
        this.percheckstatus = percheckstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.sourceType
     *
     * @return the value of wuliu_member.sourceType
     *
     * @mbggenerated
     */
    public Short getSourcetype() {
        return sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.sourceType
     *
     * @param sourcetype the value for wuliu_member.sourceType
     *
     * @mbggenerated
     */
    public void setSourcetype(Short sourcetype) {
        this.sourcetype = sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.DESC1
     *
     * @return the value of wuliu_member.DESC1
     *
     * @mbggenerated
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.DESC1
     *
     * @param desc1 the value for wuliu_member.DESC1
     *
     * @mbggenerated
     */
    public void setDesc1(String desc1) {
        this.desc1 = desc1 == null ? null : desc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.DESC2
     *
     * @return the value of wuliu_member.DESC2
     *
     * @mbggenerated
     */
    public String getDesc2() {
        return desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.DESC2
     *
     * @param desc2 the value for wuliu_member.DESC2
     *
     * @mbggenerated
     */
    public void setDesc2(String desc2) {
        this.desc2 = desc2 == null ? null : desc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.DESC3
     *
     * @return the value of wuliu_member.DESC3
     *
     * @mbggenerated
     */
    public String getDesc3() {
        return desc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.DESC3
     *
     * @param desc3 the value for wuliu_member.DESC3
     *
     * @mbggenerated
     */
    public void setDesc3(String desc3) {
        this.desc3 = desc3 == null ? null : desc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member.DESC4
     *
     * @return the value of wuliu_member.DESC4
     *
     * @mbggenerated
     */
    public String getDesc4() {
        return desc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member.DESC4
     *
     * @param desc4 the value for wuliu_member.DESC4
     *
     * @mbggenerated
     */
    public void setDesc4(String desc4) {
        this.desc4 = desc4 == null ? null : desc4.trim();
    }
}