package com.tianrui.service.bean;

public class MemberPushOwner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_push.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_push.memberid
     *
     * @mbggenerated
     */
    private String memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_push.apptype
     *
     * @mbggenerated
     */
    private Byte apptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_push.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_push.pushid
     *
     * @mbggenerated
     */
    private String pushid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_push.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_push.createtime
     *
     * @mbggenerated
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_push.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_push.modifytime
     *
     * @mbggenerated
     */
    private Long modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_push.id
     *
     * @return the value of member_push.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_push.id
     *
     * @param id the value for member_push.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_push.memberid
     *
     * @return the value of member_push.memberid
     *
     * @mbggenerated
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_push.memberid
     *
     * @param memberid the value for member_push.memberid
     *
     * @mbggenerated
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_push.apptype
     *
     * @return the value of member_push.apptype
     *
     * @mbggenerated
     */
    public Byte getApptype() {
        return apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_push.apptype
     *
     * @param apptype the value for member_push.apptype
     *
     * @mbggenerated
     */
    public void setApptype(Byte apptype) {
        this.apptype = apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_push.appid
     *
     * @return the value of member_push.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_push.appid
     *
     * @param appid the value for member_push.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_push.pushid
     *
     * @return the value of member_push.pushid
     *
     * @mbggenerated
     */
    public String getPushid() {
        return pushid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_push.pushid
     *
     * @param pushid the value for member_push.pushid
     *
     * @mbggenerated
     */
    public void setPushid(String pushid) {
        this.pushid = pushid == null ? null : pushid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_push.creator
     *
     * @return the value of member_push.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_push.creator
     *
     * @param creator the value for member_push.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_push.createtime
     *
     * @return the value of member_push.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_push.createtime
     *
     * @param createtime the value for member_push.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_push.modifier
     *
     * @return the value of member_push.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_push.modifier
     *
     * @param modifier the value for member_push.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_push.modifytime
     *
     * @return the value of member_push.modifytime
     *
     * @mbggenerated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_push.modifytime
     *
     * @param modifytime the value for member_push.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }
}