package com.tianrui.service.bean;

public class MemberPosition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_position.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_position.memberid
     *
     * @mbggenerated
     */
    private String memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_position.lat
     *
     * @mbggenerated
     */
    private Integer lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_position.lon
     *
     * @mbggenerated
     */
    private Integer lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_position.proxygps
     *
     * @mbggenerated
     */
    private String proxygps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_position.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_position.createtime
     *
     * @mbggenerated
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_position.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_position.modifytime
     *
     * @mbggenerated
     */
    private Long modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_position.id
     *
     * @return the value of member_position.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_position.id
     *
     * @param id the value for member_position.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_position.memberid
     *
     * @return the value of member_position.memberid
     *
     * @mbggenerated
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_position.memberid
     *
     * @param memberid the value for member_position.memberid
     *
     * @mbggenerated
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_position.lat
     *
     * @return the value of member_position.lat
     *
     * @mbggenerated
     */
    public Integer getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_position.lat
     *
     * @param lat the value for member_position.lat
     *
     * @mbggenerated
     */
    public void setLat(Integer lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_position.lon
     *
     * @return the value of member_position.lon
     *
     * @mbggenerated
     */
    public Integer getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_position.lon
     *
     * @param lon the value for member_position.lon
     *
     * @mbggenerated
     */
    public void setLon(Integer lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_position.proxygps
     *
     * @return the value of member_position.proxygps
     *
     * @mbggenerated
     */
    public String getProxygps() {
        return proxygps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_position.proxygps
     *
     * @param proxygps the value for member_position.proxygps
     *
     * @mbggenerated
     */
    public void setProxygps(String proxygps) {
        this.proxygps = proxygps == null ? null : proxygps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_position.creator
     *
     * @return the value of member_position.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_position.creator
     *
     * @param creator the value for member_position.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_position.createtime
     *
     * @return the value of member_position.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_position.createtime
     *
     * @param createtime the value for member_position.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_position.modifier
     *
     * @return the value of member_position.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_position.modifier
     *
     * @param modifier the value for member_position.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_position.modifytime
     *
     * @return the value of member_position.modifytime
     *
     * @mbggenerated
     */
    public Long getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_position.modifytime
     *
     * @param modifytime the value for member_position.modifytime
     *
     * @mbggenerated
     */
    public void setModifytime(Long modifytime) {
        this.modifytime = modifytime;
    }
}