package com.tianrui.service.bean;

public class MemberInfo  implements IModel{
    /**
     * 主键
     * @mbggenerated
     */
    private String id;

    /**
     * 审核人id
     * @mbggenerated
     */
    private String auditid;

    /**
     * 审核人姓名
     * @mbggenerated
     */
    private String auditname;

    /**
     * 会员表主键
     * @mbggenerated
     */
    private String memberid;

    /**
     * 手机号
     * @mbggenerated
     */
    private String phone;

    /**
     * 电话
     * @mbggenerated
     */
    private String telphone;

    /**
     * 邮箱
     * @mbggenerated
     */
    private String email;

    /**
     * 会员类型；1：企业，2：个人
     * @mbggenerated
     */
    private String membertype;

    /**
     * 真实姓名
     * @mbggenerated
     */
    private String username;

    /**
     * 身份证号码
     * @mbggenerated
     */
    private String identitycard;

    /**
     *身份证正面图片路径 
     * @mbggenerated
     */
    private String idcardsimagepath;

    /**
     * 驾驶证正面图片路径
     * @mbggenerated
     */
    private String driveimagepath;

    /**
     *企业名称 
     * @mbggenerated
     */
    private String companyname;

    /**
     * 公司所在地
     * @mbggenerated
     */
    private String companyaddress;

    /**
     * 公司联系人
     * @mbggenerated
     */
    private String companycontact;

    /**
     * 联系人手机号
     * @mbggenerated
     */
    private String contacttel;

    /**
     * 营业执照正面图片路径
     * @mbggenerated
     */
    private String licenseimagepath;

    /**
     * 审核不通过类型
     * @mbggenerated
     */
    private String rejecttype;

    /**
     * 审核不通过具体原因
     * @mbggenerated
     */
    private String rejectreason;

    /**
     * 审核时间
     * @mbggenerated
     */
    private String audittime;

    /**
     * 提交认证时间
     * @mbggenerated
     */
    private String submitdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_memberInfo.DESC1
     *
     * @mbggenerated
     */
    private String desc1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_memberInfo.DESC2
     *
     * @mbggenerated
     */
    private String desc2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_memberInfo.DESC3
     *
     * @mbggenerated
     */
    private String desc3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_memberInfo.DESC4
     *
     * @mbggenerated
     */
    private String desc4;

    /**
     * 认证编号
     * @mbggenerated
     */
    private String infocode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.ID
     *
     * @return the value of wuliu_memberInfo.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.ID
     *
     * @param id the value for wuliu_memberInfo.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.auditId
     *
     * @return the value of wuliu_memberInfo.auditId
     *
     * @mbggenerated
     */
    public String getAuditid() {
        return auditid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.auditId
     *
     * @param auditid the value for wuliu_memberInfo.auditId
     *
     * @mbggenerated
     */
    public void setAuditid(String auditid) {
        this.auditid = auditid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.auditName
     *
     * @return the value of wuliu_memberInfo.auditName
     *
     * @mbggenerated
     */
    public String getAuditname() {
        return auditname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.auditName
     *
     * @param auditname the value for wuliu_memberInfo.auditName
     *
     * @mbggenerated
     */
    public void setAuditname(String auditname) {
        this.auditname = auditname == null ? null : auditname.trim();
    }


    public String getMemberid() {
		return memberid;
	}

	public void setMemberid(String memberid) {
		this.memberid = memberid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.phone
     *
     * @return the value of wuliu_memberInfo.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.phone
     *
     * @param phone the value for wuliu_memberInfo.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.telphone
     *
     * @return the value of wuliu_memberInfo.telphone
     *
     * @mbggenerated
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.telphone
     *
     * @param telphone the value for wuliu_memberInfo.telphone
     *
     * @mbggenerated
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.email
     *
     * @return the value of wuliu_memberInfo.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.email
     *
     * @param email the value for wuliu_memberInfo.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.memberType
     *
     * @return the value of wuliu_memberInfo.memberType
     *
     * @mbggenerated
     */
    public String getMembertype() {
        return membertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.memberType
     *
     * @param membertype the value for wuliu_memberInfo.memberType
     *
     * @mbggenerated
     */
    public void setMembertype(String membertype) {
        this.membertype = membertype == null ? null : membertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.userName
     *
     * @return the value of wuliu_memberInfo.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.userName
     *
     * @param username the value for wuliu_memberInfo.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.identityCard
     *
     * @return the value of wuliu_memberInfo.identityCard
     *
     * @mbggenerated
     */
    public String getIdentitycard() {
        return identitycard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.identityCard
     *
     * @param identitycard the value for wuliu_memberInfo.identityCard
     *
     * @mbggenerated
     */
    public void setIdentitycard(String identitycard) {
        this.identitycard = identitycard == null ? null : identitycard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.idcardsImagePath
     *
     * @return the value of wuliu_memberInfo.idcardsImagePath
     *
     * @mbggenerated
     */
    public String getIdcardsimagepath() {
        return idcardsimagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.idcardsImagePath
     *
     * @param idcardsimagepath the value for wuliu_memberInfo.idcardsImagePath
     *
     * @mbggenerated
     */
    public void setIdcardsimagepath(String idcardsimagepath) {
        this.idcardsimagepath = idcardsimagepath == null ? null : idcardsimagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.driveImagePath
     *
     * @return the value of wuliu_memberInfo.driveImagePath
     *
     * @mbggenerated
     */
    public String getDriveimagepath() {
        return driveimagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.driveImagePath
     *
     * @param driveimagepath the value for wuliu_memberInfo.driveImagePath
     *
     * @mbggenerated
     */
    public void setDriveimagepath(String driveimagepath) {
        this.driveimagepath = driveimagepath == null ? null : driveimagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.companyName
     *
     * @return the value of wuliu_memberInfo.companyName
     *
     * @mbggenerated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.companyName
     *
     * @param companyname the value for wuliu_memberInfo.companyName
     *
     * @mbggenerated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.companyAddress
     *
     * @return the value of wuliu_memberInfo.companyAddress
     *
     * @mbggenerated
     */
    public String getCompanyaddress() {
        return companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.companyAddress
     *
     * @param companyaddress the value for wuliu_memberInfo.companyAddress
     *
     * @mbggenerated
     */
    public void setCompanyaddress(String companyaddress) {
        this.companyaddress = companyaddress == null ? null : companyaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.companyContact
     *
     * @return the value of wuliu_memberInfo.companyContact
     *
     * @mbggenerated
     */
    public String getCompanycontact() {
        return companycontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.companyContact
     *
     * @param companycontact the value for wuliu_memberInfo.companyContact
     *
     * @mbggenerated
     */
    public void setCompanycontact(String companycontact) {
        this.companycontact = companycontact == null ? null : companycontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.contactTel
     *
     * @return the value of wuliu_memberInfo.contactTel
     *
     * @mbggenerated
     */
    public String getContacttel() {
        return contacttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.contactTel
     *
     * @param contacttel the value for wuliu_memberInfo.contactTel
     *
     * @mbggenerated
     */
    public void setContacttel(String contacttel) {
        this.contacttel = contacttel == null ? null : contacttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.licenseImagePath
     *
     * @return the value of wuliu_memberInfo.licenseImagePath
     *
     * @mbggenerated
     */
    public String getLicenseimagepath() {
        return licenseimagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.licenseImagePath
     *
     * @param licenseimagepath the value for wuliu_memberInfo.licenseImagePath
     *
     * @mbggenerated
     */
    public void setLicenseimagepath(String licenseimagepath) {
        this.licenseimagepath = licenseimagepath == null ? null : licenseimagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.rejectType
     *
     * @return the value of wuliu_memberInfo.rejectType
     *
     * @mbggenerated
     */
    public String getRejecttype() {
        return rejecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.rejectType
     *
     * @param rejecttype the value for wuliu_memberInfo.rejectType
     *
     * @mbggenerated
     */
    public void setRejecttype(String rejecttype) {
        this.rejecttype = rejecttype == null ? null : rejecttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.rejectReason
     *
     * @return the value of wuliu_memberInfo.rejectReason
     *
     * @mbggenerated
     */
    public String getRejectreason() {
        return rejectreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.rejectReason
     *
     * @param rejectreason the value for wuliu_memberInfo.rejectReason
     *
     * @mbggenerated
     */
    public void setRejectreason(String rejectreason) {
        this.rejectreason = rejectreason == null ? null : rejectreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.auditTime
     *
     * @return the value of wuliu_memberInfo.auditTime
     *
     * @mbggenerated
     */
    public String getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.auditTime
     *
     * @param audittime the value for wuliu_memberInfo.auditTime
     *
     * @mbggenerated
     */
    public void setAudittime(String audittime) {
        this.audittime = audittime == null ? null : audittime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.submitDate
     *
     * @return the value of wuliu_memberInfo.submitDate
     *
     * @mbggenerated
     */
    public String getSubmitdate() {
        return submitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.submitDate
     *
     * @param submitdate the value for wuliu_memberInfo.submitDate
     *
     * @mbggenerated
     */
    public void setSubmitdate(String submitdate) {
        this.submitdate = submitdate == null ? null : submitdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.DESC1
     *
     * @return the value of wuliu_memberInfo.DESC1
     *
     * @mbggenerated
     */
    public String getDesc1() {
        return desc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.DESC1
     *
     * @param desc1 the value for wuliu_memberInfo.DESC1
     *
     * @mbggenerated
     */
    public void setDesc1(String desc1) {
        this.desc1 = desc1 == null ? null : desc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.DESC2
     *
     * @return the value of wuliu_memberInfo.DESC2
     *
     * @mbggenerated
     */
    public String getDesc2() {
        return desc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.DESC2
     *
     * @param desc2 the value for wuliu_memberInfo.DESC2
     *
     * @mbggenerated
     */
    public void setDesc2(String desc2) {
        this.desc2 = desc2 == null ? null : desc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.DESC3
     *
     * @return the value of wuliu_memberInfo.DESC3
     *
     * @mbggenerated
     */
    public String getDesc3() {
        return desc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.DESC3
     *
     * @param desc3 the value for wuliu_memberInfo.DESC3
     *
     * @mbggenerated
     */
    public void setDesc3(String desc3) {
        this.desc3 = desc3 == null ? null : desc3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.DESC4
     *
     * @return the value of wuliu_memberInfo.DESC4
     *
     * @mbggenerated
     */
    public String getDesc4() {
        return desc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.DESC4
     *
     * @param desc4 the value for wuliu_memberInfo.DESC4
     *
     * @mbggenerated
     */
    public void setDesc4(String desc4) {
        this.desc4 = desc4 == null ? null : desc4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_memberInfo.infoCode
     *
     * @return the value of wuliu_memberInfo.infoCode
     *
     * @mbggenerated
     */
    public String getInfocode() {
        return infocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_memberInfo.infoCode
     *
     * @param infocode the value for wuliu_memberInfo.infoCode
     *
     * @mbggenerated
     */
    public void setInfocode(String infocode) {
        this.infocode = infocode == null ? null : infocode.trim();
    }
}