package com.tianrui.service.bean;

public class MemberOwner implements IModel {
	
	private static final long serialVersionUID = -2339847197298728504L;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_member_owner.id
     *
     * @mbggenerated
     */
    private String id;
    
    /**
     * app搜索字段
     */
    private String search;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_member_owner.memberid
     *
     * @mbggenerated
     */
    private String memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_member_owner.ownerid
     *
     * @mbggenerated
     */
    private String ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_member_owner.ownername
     *
     * @mbggenerated
     */
    private String ownername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_member_owner.ownertelno
     *
     * @mbggenerated
     */
    private String ownertelno;

    /** 是否开启 */
    private String isenabled;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_member_owner.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliu_member_owner.createtime
     *
     * @mbggenerated
     */
    private Long createtime;
    
    /** 个人图像地址 */
    private String avatarsPath;
    
    /** 分页开始位置 */
    private Integer start;
    
    /** 分页数据行数 */
    private Integer limit;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member_owner.id
     *
     * @return the value of wuliu_member_owner.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member_owner.id
     *
     * @param id the value for wuliu_member_owner.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member_owner.memberid
     *
     * @return the value of wuliu_member_owner.memberid
     *
     * @mbggenerated
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member_owner.memberid
     *
     * @param memberid the value for wuliu_member_owner.memberid
     *
     * @mbggenerated
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member_owner.ownerid
     *
     * @return the value of wuliu_member_owner.ownerid
     *
     * @mbggenerated
     */
    public String getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member_owner.ownerid
     *
     * @param ownerid the value for wuliu_member_owner.ownerid
     *
     * @mbggenerated
     */
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid == null ? null : ownerid.trim();
    }

    public String getSearch() {
		return search;
	}

	public void setSearch(String search) {
		this.search = search;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member_owner.ownername
     *
     * @return the value of wuliu_member_owner.ownername
     *
     * @mbggenerated
     */
    public String getOwnername() {
        return ownername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member_owner.ownername
     *
     * @param ownername the value for wuliu_member_owner.ownername
     *
     * @mbggenerated
     */
    public void setOwnername(String ownername) {
        this.ownername = ownername == null ? null : ownername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member_owner.ownertelno
     *
     * @return the value of wuliu_member_owner.ownertelno
     *
     * @mbggenerated
     */
    public String getOwnertelno() {
        return ownertelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member_owner.ownertelno
     *
     * @param ownertelno the value for wuliu_member_owner.ownertelno
     *
     * @mbggenerated
     */
    public void setOwnertelno(String ownertelno) {
        this.ownertelno = ownertelno == null ? null : ownertelno.trim();
    }

    /**
	 * 获取是否开启
	 * @return isenabled
	 */
    public String getIsenabled() {
		return isenabled;
	}

    /**
	 * 获取是否开启
	 * @return newIsenabled
	 */
	public void setIsenabled(String newIsenabled) {
		this.isenabled = newIsenabled;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member_owner.status
     *
     * @return the value of wuliu_member_owner.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member_owner.status
     *
     * @param status the value for wuliu_member_owner.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliu_member_owner.createtime
     *
     * @return the value of wuliu_member_owner.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliu_member_owner.createtime
     *
     * @param createtime the value for wuliu_member_owner.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }
    
    /**
	 * 获取个人图像地址
	 * @return avatarsPath
	 */
    public String getAvatarsPath() {
		return avatarsPath;
	}

    /**
	 * 设置个人图像地址
	 * @param newAvatarsPath
	 */
	public void setAvatarsPath(String newAvatarsPath) {
		this.avatarsPath = newAvatarsPath;
	}

	/**
	 * 获取分页开始位置
	 * @return start
	 */
	public Integer getStart() {
		return start;
	}
	
	/**
	 * 设置分页开始位置
	 * @param newStart
	 */
	public void setStart(Integer newStart) {
		this.start = newStart;
	}
	
	/**
	 * 获取分页数据行数
	 * @return limit
	 */
	public Integer getLimit() {
		return limit;
	}
	
	/**
	 * 设置分页数据行数
	 * @param newLimit
	 */
	public void setLimit(Integer newLimit) {
		this.limit = newLimit;
	}
}