package com.tianrui.service.bean;

public class SystemMemberInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.id
     *
     * @mbggenerated
     */
    private String id;

    private String licenseType;
    private String positive;
    
    private String opposite;
    private String sex;
    private String birthday;
    private String firstlicens;
    private String licenceorg;
    private String starttime;
    private String usefullife;
    private String idcardaddress;
    private Integer pushStatus;
    private Integer ncStatus;
    //审核人  
    private String auditname;
    // 审核时间
    private Long audittime;
    
    
    public Integer getPushStatus() {
		return pushStatus;
	}

	public void setPushStatus(Integer pushStatus) {
		this.pushStatus = pushStatus;
	}

	public Integer getNcStatus() {
		return ncStatus;
	}

	public void setNcStatus(Integer ncStatus) {
		this.ncStatus = ncStatus;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.memberid
     *
     * @mbggenerated
     */
    private String memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.submittime
     *
     * @mbggenerated
     */
    private Long submittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.username
     *
     * @mbggenerated
     */
    private String username;
    /**
     * 营业执照图片
     */
    private String licenseImagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.telphone
     *
     * @mbggenerated
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.idcard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.idcardimage
     *
     * @mbggenerated
     */
    private String idcardimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.driverimage
     *
     * @mbggenerated
     */
    private String driverimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.companyname
     *
     * @mbggenerated
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.companycontact
     *
     * @mbggenerated
     */
    private String companycontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.companycode
     *
     * @mbggenerated
     */
    private String companycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.companytel
     *
     * @mbggenerated
     */
    private String companytel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.companyaddress
     *
     * @mbggenerated
     */
    private String companyaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_info.createtime
     *
     * @mbggenerated
     */
    private Long createtime;
    /**
     * 
		道路运输经营许可证号
		Road transport business license No.
     */
    private String rtblno;
    /**
     * 
		道路运输经营许可证图片
		Road transport business license No.
     */
    private String rtblimgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.id
     *
     * @return the value of member_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.id
     *
     * @param id the value for member_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.memberid
     *
     * @return the value of member_info.memberid
     *
     * @mbggenerated
     */
    public String getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.memberid
     *
     * @param memberid the value for member_info.memberid
     *
     * @mbggenerated
     */
    public void setMemberid(String memberid) {
        this.memberid = memberid == null ? null : memberid.trim();
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.submittime
     *
     * @return the value of member_info.submittime
     *
     * @mbggenerated
     */
    public Long getSubmittime() {
        return submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.submittime
     *
     * @param submittime the value for member_info.submittime
     *
     * @mbggenerated
     */
    public void setSubmittime(Long submittime) {
        this.submittime = submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.username
     *
     * @return the value of member_info.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    public String getLicenseImagePath() {
		return licenseImagePath;
	}

	public void setLicenseImagePath(String licenseImagePath) {
		this.licenseImagePath = licenseImagePath;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.username
     *
     * @param username the value for member_info.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.telphone
     *
     * @return the value of member_info.telphone
     *
     * @mbggenerated
     */
    public String getTelphone() {
        return telphone;
    }

    public String getLicenseType() {
		return licenseType;
	}

	public void setLicenseType(String licenseType) {
		this.licenseType = licenseType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.telphone
     *
     * @param telphone the value for member_info.telphone
     *
     * @mbggenerated
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.idcard
     *
     * @return the value of member_info.idcard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.idcard
     *
     * @param idcard the value for member_info.idcard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.idcardimage
     *
     * @return the value of member_info.idcardimage
     *
     * @mbggenerated
     */
    public String getIdcardimage() {
        return idcardimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.idcardimage
     *
     * @param idcardimage the value for member_info.idcardimage
     *
     * @mbggenerated
     */
    public void setIdcardimage(String idcardimage) {
        this.idcardimage = idcardimage == null ? null : idcardimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.driverimage
     *
     * @return the value of member_info.driverimage
     *
     * @mbggenerated
     */
    public String getDriverimage() {
        return driverimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.driverimage
     *
     * @param driverimage the value for member_info.driverimage
     *
     * @mbggenerated
     */
    public void setDriverimage(String driverimage) {
        this.driverimage = driverimage == null ? null : driverimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.companyname
     *
     * @return the value of member_info.companyname
     *
     * @mbggenerated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.companyname
     *
     * @param companyname the value for member_info.companyname
     *
     * @mbggenerated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.companycontact
     *
     * @return the value of member_info.companycontact
     *
     * @mbggenerated
     */
    public String getCompanycontact() {
        return companycontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.companycontact
     *
     * @param companycontact the value for member_info.companycontact
     *
     * @mbggenerated
     */
    public void setCompanycontact(String companycontact) {
        this.companycontact = companycontact == null ? null : companycontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.companycode
     *
     * @return the value of member_info.companycode
     *
     * @mbggenerated
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.companycode
     *
     * @param companycode the value for member_info.companycode
     *
     * @mbggenerated
     */
    public void setCompanycode(String companycode) {
        this.companycode = companycode == null ? null : companycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.companytel
     *
     * @return the value of member_info.companytel
     *
     * @mbggenerated
     */
    public String getCompanytel() {
        return companytel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.companytel
     *
     * @param companytel the value for member_info.companytel
     *
     * @mbggenerated
     */
    public void setCompanytel(String companytel) {
        this.companytel = companytel == null ? null : companytel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.companyaddress
     *
     * @return the value of member_info.companyaddress
     *
     * @mbggenerated
     */
    public String getCompanyaddress() {
        return companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.companyaddress
     *
     * @param companyaddress the value for member_info.companyaddress
     *
     * @mbggenerated
     */
    public void setCompanyaddress(String companyaddress) {
        this.companyaddress = companyaddress == null ? null : companyaddress.trim();
    }

    public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getBirthday() {
		return birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getFirstlicens() {
		return firstlicens;
	}

	public void setFirstlicens(String firstlicens) {
		this.firstlicens = firstlicens;
	}

	public String getLicenceorg() {
		return licenceorg;
	}

	public void setLicenceorg(String licenceorg) {
		this.licenceorg = licenceorg;
	}

	public String getStarttime() {
		return starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	public String getUsefullife() {
		return usefullife;
	}

	public void setUsefullife(String usefullife) {
		this.usefullife = usefullife;
	}

	public String getIdcardaddress() {
		return idcardaddress;
	}

	public void setIdcardaddress(String idcardaddress) {
		this.idcardaddress = idcardaddress;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_info.createtime
     *
     * @return the value of member_info.createtime
     *
     * @mbggenerated
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_info.createtime
     *
     * @param createtime the value for member_info.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

	public String getRtblno() {
		return rtblno;
	}

	public void setRtblno(String rtblno) {
		this.rtblno = rtblno;
	}

	public String getRtblimgurl() {
		return rtblimgurl;
	}

	public void setRtblimgurl(String rtblimgurl) {
		this.rtblimgurl = rtblimgurl;
	}

	public String getPositive() {
		return positive;
	}

	public void setPositive(String positive) {
		this.positive = positive;
	}

	public String getOpposite() {
		return opposite;
	}

	public void setOpposite(String opposite) {
		this.opposite = opposite;
	}

	public String getAuditname() {
		return auditname;
	}

	public void setAuditname(String auditname) {
		this.auditname = auditname;
	}

	public Long getAudittime() {
		return audittime;
	}

	public void setAudittime(Long audittime) {
		this.audittime = audittime;
	}
    
}