package com.tianrui.service.admin.mapper;

import java.util.List;

import com.tianrui.service.admin.bean.FileRoute;

public interface FileRouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_route
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_route
     *
     * @mbggenerated
     */
    int insert(FileRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_route
     *
     * @mbggenerated
     */
    int insertSelective(FileRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_route
     *
     * @mbggenerated
     */
    FileRoute selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_route
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_route
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileRoute record);
    
    List<FileRoute> selectByCondition(FileRoute record);
    long countByCondition(FileRoute record);
}