package com.tianrui.service.admin.mapper;

import java.util.List;

import com.tianrui.service.admin.bean.FileOrg;

public interface FileOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org
     *
     * @mbggenerated
     */
    int insert(FileOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org
     *
     * @mbggenerated
     */
    int insertSelective(FileOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org
     *
     * @mbggenerated
     */
    FileOrg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileOrg record);
    
    List<FileOrg> findWithCondition(FileOrg query);
    
    long countWithCondition(FileOrg query);
}