package com.tianrui.service.admin.mapper;

import java.util.List;

import com.tianrui.service.admin.bean.FileOrgCargo;

public interface FileOrgCargoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org_cargo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org_cargo
     *
     * @mbggenerated
     */
    int insert(FileOrgCargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org_cargo
     *
     * @mbggenerated
     */
    int insertSelective(FileOrgCargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org_cargo
     *
     * @mbggenerated
     */
    FileOrgCargo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org_cargo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileOrgCargo record);
    /**
     * 
     * @描述:批量修改
     * @param record
     * @return
     * @返回类型 int
     * @创建人 lsj
     * @创建时间 2016年7月20日上午11:24:39
     */
    int batchUpdateByPrimaryKeySelective(FileOrgCargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_org_cargo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileOrgCargo record);
    
    /**
     * 根据条件进行我的货物信息查询
     * <p>
     * @param record
     * @return
     * <p>
     * @author guyuke
     * @time 2016年5月22日 下午5:55:28
     */
    List<FileOrgCargo> selectMyCargoByCondition(FileOrgCargo argCondition);
    
    /**
     * 根据条件进行我的货物信息数据总量查询
     * <p>
     * @param record
     * @return
     * <p>
     * @author guyuke
     * @time 2016年5月22日 下午5:55:28
     */
    long selectCountByCondition(FileOrgCargo argCondition);
}