package com.tianrui.service.admin.mapper;

import java.util.List;

import com.tianrui.service.admin.bean.FilePositoin;

public interface FilePositoinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_position
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_position
     *
     * @mbggenerated
     */
    int insert(FilePositoin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_position
     *
     * @mbggenerated
     */
    int insertSelective(FilePositoin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_position
     *
     * @mbggenerated
     */
    FilePositoin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FilePositoin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_position
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FilePositoin record);
    
    /**
     * 
      * @Title: selectByCondition 
      * @Description: 根据条件查询 
      * @param 
      * @return List<FilePositoin>   
      * @throws 
      *
     */
    List<FilePositoin> selectByCondition(FilePositoin record);
    long countByCondition(FilePositoin record);
    
    FilePositoin selectRountename(FilePositoin record);
}