package com.tianrui.service.admin.mapper;

import java.util.List;

import com.tianrui.service.admin.bean.Mainmenu;

public interface MainmenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_mainmenu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_mainmenu
     *
     * @mbggenerated
     */
    int insert(Mainmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_mainmenu
     *
     * @mbggenerated
     */
    int insertSelective(Mainmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_mainmenu
     *
     * @mbggenerated
     */
    Mainmenu selectByPrimaryKey(Integer id);
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_mainmenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Mainmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_mainmenu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Mainmenu record);
    
    
    List<Mainmenu> selectByCondition(Mainmenu mainmenu);
    
    long countByCondition(Mainmenu mainmenu);
    
    //查询当前id  以及当前id的子节点  存在对应角色关联的数据
    List<Mainmenu> findWithRole(Integer id);
}