package com.tianrui.service.admin.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.tianrui.service.admin.bean.Role;
import com.tianrui.service.admin.bean.UserRole;
import com.tianrui.service.admin.bean.Users;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_User_Role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_User_Role
     *
     * @mbggenerated
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_User_Role
     *
     * @mbggenerated
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_User_Role
     *
     * @mbggenerated
     */
    UserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_User_Role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trwuliu_User_Role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRole record);
    
    
    int deleteByuIds(@Param("ids")List<Integer> ids);
    
    int deleteByrId(Integer rid);
    
    List<Role> findWithUId(Integer uId);
    
    List<Users> findWithRId(Integer rId);
    
    List<Users> findWithRIds(@Param("rIds")List<Integer> rIds);
}